version: "3.9"
services:
  api:
    build: ../apps/api
    ports: ["8000:8000"]
    env_file: ../apps/api/.env.local
  neo4j:
    image: neo4j:5
    ports: ["7474:7474","7687:7687"]
    environment:
      NEO4J_AUTH: neo4j/neo4jtest
    volumes:
      - neo4j_data:/data
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite -l /data -s"
    ports: ["10000:10000","10001:10001","10002:10002"]
    volumes:
      - azurite_data:/data
volumes:
  neo4j_data:
  azurite_data:
